# numpy index and selection

In [1]:
import numpy as np

In [2]:
rand_arr = np.random.randint(1,100,25)

In [3]:
rand_arr.reshape(5,5)

array([[23, 90, 82, 99, 76],
       [45, 60, 76, 77, 62],
       [42, 63, 45, 21, 49],
       [89, 27, 10, 54, 91],
       [53, 58, 69,  7, 42]])

In [4]:
arr= np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:

np.linspace(2,5,10)

array([ 2.        ,  2.33333333,  2.66666667,  3.        ,  3.33333333,
        3.66666667,  4.        ,  4.33333333,  4.66666667,  5.        ])

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[:3]=100

In [9]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [10]:
arr2= np.arange(0,11)

In [11]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr2[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_array=arr2[2:5]
slice_of_array
arr3=arr2.copy()

In [15]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_array

array([2, 3, 4])

In [17]:
# 2 dimentinal matrix 
arr_do=np.arange(0,25,1)
arr_do

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
arr_2d =arr_do.reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr_2d.shape

(5, 5)

In [20]:
arr_2d[2][2]

12

In [21]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
arr_2d[3,3]

18

In [23]:
arr_2d[2:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [25]:
arr_2d[3:,2:]

array([[17, 18, 19],
       [22, 23, 24]])

In [30]:
arr_1d=arr_2d.reshape(25)

In [37]:
bool_arr_1d =arr_1d >3

In [39]:
bool_arr_1d

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [40]:
arr_1d[bool_arr_1d]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24])

In [41]:
arr_1d[arr_1d >3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24])

In [47]:
arr3= np.arange(50).reshape(5,10)

In [48]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [49]:
arr3[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [53]:
arr3[1:3,3:5]

array([[13, 14],
       [23, 24]])