#numpy introduction and use case


#numPy array

In [1]:
my_list=[1,2,3,4,5,6]

In [2]:
my_list

[1, 2, 3, 4, 5, 6]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3, 4, 5, 6])

In [5]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
my_mat2=[[2,3],[4,5,6],[7,8,9]]

In [6]:
my_mat,my_mat2

([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.array(my_mat2)

array([list([2, 3]), list([4, 5, 6]), list([7, 8, 9])], dtype=object)

In [9]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [17]:
np.zeros((2,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [12]:
np.ones(13)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [16]:
#linspace is array generator with start stop and sampleside (evenly space no) you want

np.linspace(3,3.2,100)

array([ 3.        ,  3.0020202 ,  3.0040404 ,  3.00606061,  3.00808081,
        3.01010101,  3.01212121,  3.01414141,  3.01616162,  3.01818182,
        3.02020202,  3.02222222,  3.02424242,  3.02626263,  3.02828283,
        3.03030303,  3.03232323,  3.03434343,  3.03636364,  3.03838384,
        3.04040404,  3.04242424,  3.04444444,  3.04646465,  3.04848485,
        3.05050505,  3.05252525,  3.05454545,  3.05656566,  3.05858586,
        3.06060606,  3.06262626,  3.06464646,  3.06666667,  3.06868687,
        3.07070707,  3.07272727,  3.07474747,  3.07676768,  3.07878788,
        3.08080808,  3.08282828,  3.08484848,  3.08686869,  3.08888889,
        3.09090909,  3.09292929,  3.09494949,  3.0969697 ,  3.0989899 ,
        3.1010101 ,  3.1030303 ,  3.10505051,  3.10707071,  3.10909091,
        3.11111111,  3.11313131,  3.11515152,  3.11717172,  3.11919192,
        3.12121212,  3.12323232,  3.12525253,  3.12727273,  3.12929293,
        3.13131313,  3.13333333,  3.13535354,  3.13737374,  3.13

In [15]:
#identity matrix in numpy medhod name eye
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [18]:
np.random.rand(5)

array([ 0.38481481,  0.74522753,  0.11372498,  0.89249208,  0.94648933])

In [19]:
np.random.rand(3,4)

array([[ 0.53191004,  0.51574745,  0.78167613,  0.94077139],
       [ 0.94121771,  0.15104708,  0.70289999,  0.05032673],
       [ 0.97941059,  0.2148669 ,  0.76970994,  0.85032608]])

In [20]:
np.random.rand(2,3,4)

array([[[  8.84150193e-01,   4.06056682e-01,   2.52406354e-01,
           4.89405234e-01],
        [  4.45548018e-02,   1.90835861e-01,   9.29530149e-01,
           3.35200438e-01],
        [  6.58427120e-04,   1.46296034e-01,   4.46050606e-01,
           4.16215315e-01]],

       [[  6.62869513e-01,   5.97294479e-01,   2.57530933e-01,
           4.16503021e-01],
        [  8.82246454e-01,   6.12797051e-01,   2.86654299e-01,
           8.44733613e-01],
        [  1.42847231e-01,   4.92630311e-02,   8.04783947e-01,
           3.02654576e-01]]])

In [21]:
np.random.randn(3,4)

array([[ 1.31923899, -0.01855081,  0.6651252 , -0.2002372 ],
       [ 0.7574445 , -0.11510485,  0.15238137, -2.72218025],
       [-0.30446246,  1.17118907, -0.85233475,  1.45545488]])

In [23]:
np.random.randint(2,100)

39

In [24]:
np.random.randint(2,100,30)

array([26, 26, 31, 99, 93, 31, 39, 64, 78, 56, 42, 35, 87, 25, 84, 38, 40,
       74, 95, 14, 26, 80,  4, 43, 44, 31, 51, 54, 54, 33])

In [25]:
arr = np.random.randint(1,100,25)

In [26]:
arr

array([59, 76,  3, 12, 76, 18, 90, 60, 34,  3, 96, 79, 32, 65, 57, 36, 30,
        9, 41,  5, 16, 71, 81, 29, 17])

In [28]:
arr2 = arr.reshape(5,5)

arr2

In [36]:
arr2

array([[59, 76,  3, 12, 76],
       [18, 90, 60, 34,  3],
       [96, 79, 32, 65, 57],
       [36, 30,  9, 41,  5],
       [16, 71, 81, 29, 17]])

In [37]:
arr2.max()

96

In [38]:
arr2.min()

3

In [39]:
arr2.argmax()

10

In [41]:
arr2.shape

(5, 5)

In [42]:
arr2.size

25