In [2]:
import numpy as np
from sklearn.cross_validation import train_test_split

In [3]:
X,y= np.arange(10).reshape((5,2)),range(5)

In [4]:
np.arange(10).reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
y

range(0, 5)

In [7]:
for i in range(5):
    print(i)

0
1
2
3
4


In [8]:
list(y)

[0, 1, 2, 3, 4]

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [10]:
X_test

array([[4, 5],
       [8, 9]])

In [11]:
X_train

array([[0, 1],
       [6, 7],
       [2, 3]])

In [28]:
from sklearn.linear_model import  LinearRegression

In [29]:
model = LinearRegression(normalize=True)

In [30]:
print(model)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)


In [31]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [32]:
Predictions=model.predict(X_test,)

In [36]:
Predictions

array([ 2.,  4.])

In [37]:
model.score(X_train,y_train)

1.0